---
title: Orlando Designers
timezone: America/New_York
collections:
  events:
    title: Events
    output: false
    permalink: "/events/:path/"
  meetups:
    title: Meetups
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: events
    start_date: ''
    end_date: ''
    location_name: ''
    address: ''
    link: ''
email: dustin@delatore.me
description: 'Orlando Designers Slack is a place for designers who live or work in
  Orlando to chat and support each other.

'
baseurl: 
url: http://example.com
markdown: kramdown
permalink: "/:title/"
