---
title: Orlando Designers
timezone: UTC
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: events
    start_date: ''
    end_date: ''
    link: ''
email: dustin@delatore.me
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://example.com
markdown: kramdown
permalink: "/:title/"
