---
title: Orlando Designers
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: false
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  meetups:
    title: Meetups
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: posts
    perlink: "/:category/:path/"
- scope:
    path: ''
    type: events
  values:
    layout: events
    start_date: ''
    end_date: ''
    location_name: ''
    address: ''
    link: ''
- scope:
    path: ''
    type: meetups
  values:
    link: ''
email: dustin@delatore.me
description: 'Orlando Designers Slack is a place for designers who live or work in
  Orlando to chat and support each other.

'
<<<<<<< HEAD
baseurl:
url: http://example.com
=======
baseurl: 
url: https://orlandodesigners.info
>>>>>>> 60f1f80cea1d25d91a9e7ff8ffae483e7cbbda5c
markdown: kramdown
permalink: pretty
gems:
- jekyll-sitemap
- jekyll-redirect-from
