---
title: Orlando Designers
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: false
  duration:
    title: Duration
    output: true
  events:
    title: Events
    output: true
    permalink: "/events/:path/"
  jobs:
    title: Jobs
    output: true
  meetups:
    title: Meetups
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: posts
- scope:
    path: ''
    type: events
  values:
    layout: events
    start_date: ''
    end_date: ''
    location_name: ''
    address: ''
    link: ''
- scope:
    path: ''
    type: meetups
  values:
    link: ''
email: dustin@delatore.me
description: 'Orlando Designers Slack is a place for designers who live or work in
  Orlando to chat and support each other.

'
baseurl: 
url: https://orlandodesigners.info
markdown: kramdown
permalink: "/:categories/:title/"
gems:
- jekyll-sitemap
- jekyll-redirect-from
